apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: app
data:
  DB_HOST: postgres.database.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: app_db
  API_HOST: http://backend:5000
  API_PORT: "5000"